### ISSUE TITLE
Option '-f' and partial downloads (soundcloud)

### ISSUE THREAD

**Issue by Lanchon** [Miserlou/SoundScrape#100]
hi,

thanks for SoundScrape!

i use it with the `-f` option. sometimes a download hangs and i have to interrupt the script (usually ctrl-c). this leaves an incomplete, corrupted download file in the local library, causing two issues:

- my player will attempt to play the corrupted download.
- more importantly, when i retry the `soundscrape -f` command, **the corrupted download is skipped entirely** (instead of being retried or continued) leaving the corrupted file in the library forever.

these issues are easy to fix. a workable solution is:

- use a temporary filename while downloading files. make sure the extension does not match any recognizable music extension to lessen the chance that a player will pick it up. if applicable, lock the file against reading by other processes for the same reason. downloading to /tmp or equivalent can also be considered.
-  if the temporary filename generation policy can result in clashes with previous download attempts, then silently overwrite any existing temporary files.
- for even cleaner behavior, register a termination callback or equivalent to remove the temporary file currently being downloaded if there is one. (ideally ctrl-c should remove the temp download.)

thanks!

**Comment by Miserlou** [comment]
We might be able to do one better and make sure that the expected filesize of the track to be downloaded matches the file size of the track already downloaded. Good bug, thanks for reporting.

**Comment by Lanchon** [comment]
yes, i thought of that, but i though metadata download could complicate that option.

**Comment by Miserlou** [comment]
Yeah, you're right, the custom stuff in the ID3 sinks that approach. Trying with temporary files.

**Comment by Lanchon** [comment]
the temp files are ok.

but later you can also do this: you can add a custom ID3 tag with the original length. you can also include other info returned from the server, such as hash, last modified date, version or whatever. so when you re-check you can verify that these attributes match. this would be more of a sync, and exceeds the scope of this issue.

speaking about sync, it would be nice to have a different '-f' option that structures files according to soundcould's IDs. say, directory and file names would probably be numeric. the textual attributes (user name, track name, track list name, etc) would be used only to tag the files. ideally, the sync would detect change in attributes and retag the existing files. right now if a song name changes, -f redownloads it and leaves both copies in the library. and if other attributes not used to name the file change, the ID3 tag of the file goes stale with the old info.

**Comment by Miserlou** [comment]
I think this was fixed in 0.27.0 and I forgot to close the issue, whoops!
