### ISSUE TITLE
Some URLs silently fail to download (soundcloud)

### ISSUE THREAD

**Issue by Lanchon** [Miserlou/SoundScrape#102]
running these commands cause no downloads, but the corresponding URLs work:

```
soundscrape -f https://soundcloud.com/themagician/sets/magic-tapes
soundscrape -f https://soundcloud.com/sashaofficial/tracks
```

these commands used to work a while back.

**Comment by Miserlou** [comment]
Good find. Not sure what's happening with the first one.

The second can be retrieved with `soundscrape -f sashaofficial` thought. The preview tracks should be skipped by default.

**Comment by Lanchon** [comment]
thanks for the sashaofficial tip!

**Comment by Miserlou** [comment]
The first one is another instance of the old SoundCloud API lying about the results, so it has to be manually scraped. A starting point.. https://api-v2.soundcloud.com/playlists/1054858?representation=full&client_id=02gUJC0hH2ct1EGOcYXQIzRFU91c72Ea&app_version=1467724310
