### ISSUE TITLE
Make an Automator / AppleScript ~GUI with input box?

### ISSUE THREAD

**Issue by profucius** [Miserlou/SoundScrape#105]
First, I'm loving SoundScrape!

I had an idea. There must be a way to create an Automator or AppleScript (OSX) that first asks the user to enter what artist or album or URL they want to download using SoundScrape. This input then passes to the command, and automatically downloads.

This would bypass the need to open Terminal every time, and make it into an .app for being more user friendly. I'm unfortunately very novice at scripting, so I'm not sure how to set this up. 

I do know how to use Automator pretty effectively, so if anyone can help me bridge the shell script and the user input command into Automator, I know how to create the flow and make the .app

Dev, or anyone else?

**Comment by Miserlou** [comment]
I'm fine with this idea, or using flexx/cefthon for a cross-platform solution, but somebody else will have to spearhead it as I'm a command-line kinda guy..

**Comment by SimplicityGuy** [comment]
This is a very old request, and unrelated to SoundScrape itself. Other tools, for example, `youtube-dl` have a UI project that is not associated with the original project. Seems like this can be handled the same way here if there's interest.
