### ISSUE TITLE
Can we set a folder to download to?

### ISSUE THREAD

**Issue by long-horse** [Miserlou/SoundScrape#106]
Currently it downloads to ~/Me/ but I'd like to be able to change that.

**Comment by Miserlou** [comment]
This is a good idea. It currently just downloads to `pwd`. It should
probably support -P and/or -O, like `wget`.

**Comment by brachna** [comment]
I think this should be closed now, unless there's something wrong with the commit.

**Comment by long-horse** [comment]
I'm fine with closing it but I did `pip install soundscrape --upgrade` and then `soundscrape -h` and I don't see anything about setting a folder :| is it added but the update hasn't been pushed yet?

**Comment by brachna** [comment]
Hmm, maybe pip just didn't updated yet. I just tried installing like you did. Got error at first, and it's an older file.
Shoud be open until resolved.

**Comment by long-horse** [comment]
I have v0.28.2, is that what I should have or do I need to wait a bit longer till the update is available for me?

**Comment by brachna** [comment]
Checking pypi - v0.28.2 was on 2016-09-04. That's ooold.
If you're impatient you can download soundscrape.py from current master and just copy-paste it into your "<PythonPath>/Lib/site-packages/soundscrape" path. Or just wait till Miserlou updates it.

**Comment by Miserlou** [comment]
Sorry guys, I merged but didn't bump the published version. Published 0.29.0 but I didn't test it very thoroughly. :[

**Comment by long-horse** [comment]
Works now! Need the -p path every time but it works :)
