### ISSUE TITLE
Sets not downloading

### ISSUE THREAD

**Issue by long-horse** [Miserlou/SoundScrape#107]
I tried `soundscrape https://soundcloud.com/ollyjamesmusic/sets/send-your-beatport-receipts-to` and Terminal waited a few seconds until starting a new line with `MacBook:~ Me$` indicating it didn't download it.

Edit: I tried a set with multiple songs and it worked. Maybe it doesn't download sets with one track?

**Comment by Miserlou** [comment]
It looks like that set doesn't exist, could that be why?

**Comment by long-horse** [comment]
Well it did when I posted this, I guess you can disregard this unless another broken playlist pops up.

**Comment by Miserlou** [comment]
Okay, thanks for reporting! Let me know if anything else comes up.

**Comment by long-horse** [comment]
Found another set that doesn't download https://soundcloud.com/datweekaz/sets/tweekay16

**Comment by Miserlou** [comment]
Works for me [OSX] - can you try

pip install soundscrape --upgrade

**Comment by Miserlou** [comment]
Oops, never mind, I get the same error as you do. Hm.

**Comment by Miserlou** [comment]
I think they've maybe they nuked the new API key..

**Comment by long-horse** [comment]
But why does it work on Windows if they patched your API key

**Comment by Miserlou** [comment]
Looks like the files downloaded okay on OSX, not sure why though..
