### ISSUE TITLE
download fails, if artist's name contains a forward slash 

### ISSUE THREAD

**Issue by tziplop** [Miserlou/SoundScrape#108]
if the artists name contains a forward slash it fails to download, because it wants to save the file with the whole artists name, including the slash. wich obviously fails in linux-systems..

**Comment by Miserlou** [comment]
Can you give me an example artist to test against? That should be sanitized.

**Comment by tziplop** [comment]
Ah, this is a bandcamp-only issue. I just tested it on Soundcloud and it works fine there.
On bandcamp it doesn't work, when the artist or title contains a forward slash:
example for title: https://chingliu.bandcamp.com/track/--6
example for artist: http://dotx3dashx2.bandcamp.com/releases
when the album name contains a forward slash it works fine: 
example for album : https://fiturings.bandcamp.com/album/-

**Comment by Miserlou** [comment]
Hopefully this is fixed on 0.27.3

**Comment by tziplop** [comment]
it works for me now with bandcamp on linux - thanks!

**Comment by Miserlou** [comment]
Great, thanks for reporting and for confirming the fix! Let me know if you find any other bugs, etc.
