### ISSUE TITLE
downloading bandcamp album with -f results in creating mp3s outside of the album folder

### ISSUE THREAD

**Issue by brachna** [Miserlou/SoundScrape#113]
Seems like the line
path = sanitize_filename(path)
in
def scrape_bandcamp_url(url, num_tracks=sys.maxsize, folders=False)
is unnecessary?

path "album/track.mp3" turns into "album-track.mp3"

directory and track_filename are already sanitized prior to join()

**Comment by Miserlou** [comment]
Thanks for your fix, sorry for the delay!

Thanks for your contribution, I hope you keep contributing to free software in the future!!!!

**Comment by Sikksens** [comment]
Hey there, I seem to still be having this problem when using the -f argument.

**Comment by Miserlou** [comment]
Did you

    pip install soundscrape --upgrade

? Can you give me an example artist

**Comment by Sikksens** [comment]
I reinstalled today so should be the latest
This is the Album I was trying to scrape:
https://blood-music.bandcamp.com/album/the-uncanny-valley-bonus

It makes the folder ok but places the audio files outside of it.

**Comment by Miserlou** [comment]
Should be fixed now.

**Comment by brachna** [comment]
I probably messed up something when doing a pull. Still new to this.
