### ISSUE TITLE
Wrong artist in case of non-produced track

### ISSUE THREAD

**Issue by cfollet** [Miserlou/SoundScrape#118]
If someone post a track who doesn't belong to him and put `Artist - Title` as a title, we have to take into account that `Artist` is the artist and not the user who posted the track.

While calculating the title during the ID3 identification, why not check if a dash `-` exists? If it's the case, the first substring is the `Artist` and the other the `Title`

Example : [Fouk - Orchard (STW Premiere)](https://soundcloud.com/stampthewax/fouk-orchard)

**Comment by Miserlou** [comment]
Yeah, this is a good idea but it doesn't work in practice, I'm sorry. There are so many tracks that use different formats, there are songs that have '-' in their titles, some art Artist - Track, some are Track - Artist, etc. It's a wild goose chase. :[

**Comment by cfollet** [comment]
You are right, no problem. Good job anyway for your excellent script.

**Comment by Miserlou** [comment]
Thanks! Please report any other issues you find!
