### ISSUE TITLE
HttpError from requests

### ISSUE THREAD

**Issue by hangtwenty** [Miserlou/SoundScrape#12]
Thanks for writing this, great idea!

Currently having issues, using Python 2 on Arch Linux. Installed via Python 2 pip (`pip2` in Arch usually) and ensured I have appropriate version of requests.

But I get 404s for some reason when trying to download this mix.

```
$ soundscrape dazedandconfused -t "Zola Jesus - T U N D R A"
Traceback (most recent call last):
  File "/usr/bin/soundscrape", line 9, in <module>
    load_entry_point('soundscrape==0.10.0', 'console_scripts', 'soundscrape')()
  File "/usr/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 50, in main
    resolved = client.get('/resolve', url=artist_url)
  File "/usr/lib/python2.7/site-packages/soundcloud/client.py", line 130, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "/usr/lib/python2.7/site-packages/soundcloud/request.py", line 134, in make_request
    result.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 765, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found
 
$ soundscrape https://soundcloud.com/dazedandconfused/zola-jesus-t-u-n-d-r-a
Downloading: Zola Jesus – T U N D R A
Problem downloading Zola Jesus – T U N D R A
404 Client Error: Not Found
```

Please let me know if I can provide more information for you.

**Comment by Miserlou** [comment]
Another example just bit me: https://soundcloud.com/wmstrecs/lightning-bolt-barbarian-boy

**Comment by xHN35RQ** [comment]
> Another example just bit me: https://soundcloud.com/wmstrecs/lightning-bolt-barbarian-boy

this works fine for me. did soundcloud change it from rtmp to mp3 and when did they do so?

**Comment by Odinxcore** [comment]
I'm really new to python, but when I used the artists name to download, it gives me that 404 error as well.
I just used the URL for the album I wanted and it worked just fine.
Hope that is useful input.

**Comment by Miserlou** [comment]
All these tracks work now.
