### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by eN0Rm** [Miserlou/SoundScrape#123]
I try to install SoundScrape with pip in a virtualenv, but I get some errors, manly:

`Failed building wheel for cryptography`

`Failed cleaning build dir for cryptography`

`Failed building wheel for cffi`

`Command "/home/fredrik/dev.py/soundScrape/venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-BsVYs9/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Wmkg96-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/fredrik/dev.py/soundScrape/venv/include/site/python2.7/cffi" failed with error code 1 in /tmp/pip-build-BsVYs9/cffi/
`

This is the whole output from the install 
[out.txt](https://github.com/Miserlou/SoundScrape/files/456297/out.txt)

What is wrong?

**Comment by Miserlou** [comment]
Shit, does brew help?

https://groups.google.com/forum/#!msg/python-cffi/gRiL5pSHKnc/8Y-6ZzrXcwAJ

**Comment by Miserlou** [comment]
Oh, I'm assuming you're on OSX. Is that the case?

**Comment by eN0Rm** [comment]
Sorry for late reply, I'm on Ubuntu 16.04.

**Comment by Neko250** [comment]
Try with `sudo apt-get install python-cffi libffi-dev`

**Comment by SimplicityGuy** [comment]
Unrelated to SoundScrape, however the previous comment addresses this. `cryptography` package has good documentation on how to fix these sorts of problems.
