### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Alexey1100** [Miserlou/SoundScrape#125]
Hi there.
Have a problem with such urls:

`$ soundscrape https://www.mixcloud.com/n10as/editorial-❶-13032016/`

```
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 74, in main
    if 'bandcamp.com' in artist_url or vargs['bandcamp']:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 41: ordinal not in range(128)

```

Works fine only after converting url to punycode:
`$ soundscrape https://www.mixcloud.com/n10as/editorial-%E2%9D%B6-13032016/`

**Comment by Miserlou** [comment]
Dang, that's a great bug.

**Comment by Miserlou** [comment]
This music is nice too.

**Comment by Miserlou** [comment]
Can you please submit a PR that punyencodes all incoming unicode URLS? Thanks!!

**Comment by Alexey1100** [comment]
🙃

Okay, created request.

**Comment by Alexey1100** [comment]
🙃

Okay, created request.

**Comment by brachna** [comment]
Script doesn't work now on Windows, Python 3.5. I get "'str' object has no attribute 'decode'"
If I remove change from #126, then it works, but of course not with urls that need punycode.

**Comment by Alexey1100** [comment]
Yeah, looks like they removed .decode() method from Python 3.
