### ISSUE TITLE
AssertionError: sorry, but this version only supports 100 named groups

### ISSUE THREAD

**Issue by AwolDes** [Miserlou/SoundScrape#130]
Installed the package on Ubuntu 16.04 and it worked fine, but just tried installing it on Kubuntu 16.04 and when I `pip install soundscrape` I get hit with the above error. [Here's a link to a gist](https://gist.github.com/AwolDes/8ca22c66c4aee02e555a58c894aed1d5) with the complete trace. 

Love the project man :)

**Comment by Miserlou** [comment]
Try `sudo apt-get install python-cffi libffi-dev`

**Comment by AwolDes** [comment]
Unfortunately it still fails in the same way. I realise this isn't a problem with your project, but thanks for the help mate.

**Comment by SimplicityGuy** [comment]
This is unrelated to SoundScrape and looks related to the `cryptogrpahy` package. That package has great information on how to get dependencies installed for various platforms.
