### ISSUE TITLE
u'artFullsizeUrl' error in Bandcamp

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/SoundScrape#133]
sof https://ozziebeats.bandcamp.com/album/september

Downloading: Hero (Instrumental)
[################################] 3292/3292 - 00:00:01
Problem downloading Hero (Instrumental)
u'artFullsizeUrl'
Downloading: Beneath (Instrumental)
[################################] 2838/2838 - 00:00:03
Problem downloading Beneath (Instrumental)
u'artFullsizeUrl'
Downloading: Candy Floss (Instrumental)
[################################] 2582/2582 - 00:00:02
Problem downloading Candy Floss (Instrumental)
u'artFullsizeUrl'
Downloading: Forgranted (Instrumental)
[################################] 3748/3748 - 00:00:03
Problem downloading Forgranted (Instrumental)
u'artFullsizeUrl'

**Comment by brachna** [comment]
Was 'artFullsizeUrl' in 'var TralbumData = { ...' before?
It's not there anymore, maybe they have updated bandcamp.

**Comment by Miserlou** [comment]
Yeah, this is probably an update to the data format they supply.

**Comment by Zibbk** [comment]
same error. i did everythin but nothin to change. can anyone help me? thanks.

**Comment by Miserlou** [comment]
pip install soundscrape --upgrade

**Comment by Zibbk** [comment]
worked. Thanks a lot for your support00:57, 9 Ocak 2017, Rich Jones <notifications@github.com>:pip install soundscrape --upgrade

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




Yandex.Mail mobil sürümünden gönderildi: http://m.ya.ru/ymail

**Comment by Zibbk** [comment]
worked, thanks a lot for your support. 
i had one more problem, how can i download covers from bandcamp with soundscrape?

**Comment by Miserlou** [comment]
Post one that doesn't work?

**Comment by Zibbk** [comment]
didnt see, can you share link?

**Comment by brachna** [comment]
@Zibbk you mean you want to save cover separately into a graphic file, not just inside mp3 files?

**Comment by Miserlou** [comment]
I'm saying that bandcamp art works for me. If you find one that doesn't work, you'll have to post it. In a new Issue, please.
