### ISSUE TITLE
No ID3 tags? 

### ISSUE THREAD

**Issue by XavierSchiller** [Miserlou/SoundScrape#137]
So, Whenever I download from sound cloud  - I've only tested there so far - I don't see any of the ID3 tags (Not even the Album Art) on my *.mp3 file?

**Comment by Miserlou** [comment]
Please post the track to reproduce on.

**Comment by XavierSchiller** [comment]
Link: https://soundcloud.com/mattiacupelli/two-souls
Command Issued:
Soundscrape https://soundcloud.com/mattiacupelli/two-souls 

Outputs:

Active code page: 65001
Downloading: Shades
[################################] 4755/4755 - 00:00:04

And that's it.

**Comment by Miserlou** [comment]
Cannot reproduce, works fine for me.

Try `pip install soundscrape --upgrade` and try again?
