### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by alextrastero** [Miserlou/SoundScrape#139]
![screen shot 2016-10-18 at 18 48 47](https://cloud.githubusercontent.com/assets/4152819/19487522/8d2c692e-9563-11e6-9bc0-bea20cf97aec.png)
Any ideas?

**Comment by alextrastero** [comment]
after running `pip install soundscrape`

**Comment by Miserlou** [comment]
What OS?

**Comment by alextrastero** [comment]
Mac os sierra

**Comment by Miserlou** [comment]
Python version?

**Comment by alextrastero** [comment]
2.7 i thinks

**Comment by alextrastero** [comment]
I did brew install Python

**Comment by Miserlou** [comment]
Can you `pip install mutagen` succesfully?

**Comment by adiq** [comment]
@alextrastero works fine when installing via easy_install

**Comment by alextrastero** [comment]
Thanks

**Comment by martin-ro** [comment]
I'm having the same error. I did used easy_install to install pip.

macOS Sierra 10.12.3
Python 2.7.10
pip 9.0.1

**Comment by martin-ro** [comment]
welp..

`sudo -H pip install --install-option '--install-data=/usr/local' soundscrape`

worked for me.

**Comment by adiq** [comment]
@martin-ro did you ran sudo easy_install mutagen? And then regular pip install?
