### ISSUE TITLE
UnicodeDecodeError - so lost

### ISSUE THREAD

**Issue by slackeroni** [Miserlou/SoundScrape#140]
a friend of mine introduced me to soundscrape, and pretty much walked me through the whole process, I initially installed python 2.7.11 since it was working perfectly for him, and I further progressed to installing soundcrape on cmd upgrading it, now where i hit a brick wall is that when I attempted to download a few songs I kept getting an error:
C:\Users\pejma>soundscrape https://soundcloud.com/doucefrance/pulsometre
Active code page: 65001
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\soundscrape.exe__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 113, in main
    process_soundcloud(vargs)
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 283, in process_soundcloud
    id3_extras=id3_extras)
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 452, in download_tracks
    puts_safe(colored.red("Problem downloading ") + colored.white(track['title']))
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 1153, in puts_safe
    puts(text.encode(sys.stdout.encoding, errors='replace').decode())
  File "c:\python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 56: ordinal not in range(128)

Now whats really odd, even though i went through the same process as my friend did, he was able to download that particular file, and according to him, he didnt get the active code page: 65001 when trying to download.

**Comment by brachna** [comment]
Downloaded fine here. The first e in pulsometre is unicode, so it should print Pulsom?tre, but in your case it can't for some reason and generates an error.
Try upgrading with "pip install soundscrape --upgrade".
If it doesn't help, try with latest Python 3.5.2 instead of 2.7.11.

I think print(e) on line 453 should be deleted, because it will try to print unicode characters and crash on Windows.

**Comment by bluesodium** [comment]
i get this when its the 2nd time i run soundscrape in the same cmd window.

**Comment by Dom-R** [comment]
Quick fix for me was to comment like 1153
```
def puts_safe(text):
    if sys.platform == "win32":
        #puts(text.encode(sys.stdout.encoding, errors='replace').decode())
        puts(text)
    else:
        puts(text)
```

**Comment by jorge705** [comment]
python -m pip install -U pip

<3

**Comment by Miserlou** [comment]
Sorry are you guys trying to say that the code somebody added to make it work on Windows is the thing that's breaking it on Windows?

**Comment by Dom-R** [comment]
Yes. At least for me it crashes everytime there is a special character like 'Ø'. (Windows 10 Home x64)

**Comment by brachna** [comment]
@Dom-R 
That was added by me and for a reason.
python soundscrape.py -f "https://soundcloud.com/doucefrance/pulsometre"
crashes for me if I apply your modification.

**Comment by bluesodium** [comment]
Bizarrely for me. soundscrape works fine first time i run it.
Every subsequent run it errors (windows Python 2.7. updated PIP using python -m pip install -U pip):

Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\soundscrape.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 113, in
main
    process_soundcloud(vargs)
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 283, in
process_soundcloud
    id3_extras=id3_extras)
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 452, in
download_tracks
    puts_safe(colored.red("Problem downloading ") + colored.white(track['title']
))
  File "c:\python27\lib\site-packages\soundscrape\soundscrape.py", line 1153, in
 puts_safe
    puts(text.encode(sys.stdout.encoding, errors='replace').decode())
LookupError: unknown encoding: cp65001

looks like a pip error..

**Comment by brachna** [comment]
@bluesodium 
I'm gonna make pull request soon with new fixes. Give it a try then, I think I fixed the issue.

**Comment by bluesodium** [comment]
Dom-R fixes it for me

**Comment by brachna** [comment]
Perhaps Python 2 doesn't support it.
Can you run following lines in the Python Shell and tell the result:
import sys
"Pulsomètre".encode(sys.stdout.encoding, errors='replace').decode()

**Comment by bluesodium** [comment]
here you go:

  File "C:\Python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8a in position 6: ordinal
not in range(128)

**Comment by brachna** [comment]
I see.
Can you try with these 3 lines now, please.
import os, sys
os.system("chcp 65001")
"Pulsomètre".encode(sys.stdout.encoding, errors='replace').decode()

Do you get the same error?

**Comment by bluesodium** [comment]
no, it bombs out of the python shell, back to the regular command line

**Comment by brachna** [comment]
Updated my pull. Thank you for testing.

**Comment by bluesodium** [comment]
this works though...

print("Pulsomètre".decode(sys.stdout.encoding).encode('utf-8',errors='replace').decode('utf-8'))

**Comment by brachna** [comment]
Problem is str objects don't have decode() method in Python 3.
If pull is accepted then Python 2 will simply use puts(text).

**Comment by Miserlou** [comment]
Cross-platform, cross-version unicode bugs. A perfect storm of Python shit.

Thanks for riding this one out guys, looking at the PR now..

**Comment by slackeroni** [comment]
Hey folks wow i havent been active on guthub for the past few weeks just got on today and was shocked with the number of replies, i tried the suggestion that brachna gave and it totally worked fine i guess the previous version of python had trouble decoding the foreign fonts, as now in CMD it just read the name as some weird lettering

**Comment by snizzleorg** [comment]
this still seems to be problematic - right? I get
```
UnicodeEncodeError: 'ascii' codec can't encode character '\xc9' in position 55: ordinal not in range(128)
```

Python 2.7...

**Comment by dseptem** [comment]
I still have problems like these, and I'm using python 3.7 on Windows.

Is there any kind of fix available?

**Comment by dseptem** [comment]
I think this is the root of the problem: https://github.com/tartley/colorama/issues/155

**Comment by SimplicityGuy** [comment]
This was fixed a while ago, and also addressed as part of a dependent package.
