### ISSUE TITLE
Download album art

### ISSUE THREAD

**Issue by konsbn** [Miserlou/SoundScrape#142]
How do I download the album art using soundscrape. I understand this is not as much an issue as it is a dumb question but I did not know where else to ask.

**Comment by ThaMunsta** [comment]
If album art could be added to ID3 tags that would be fantastic!

**Comment by Miserlou** [comment]
It already does? Are there examples of it not working?

**Comment by ThaMunsta** [comment]
I've never had it add ID3 tags to my downloads. Is there a command I can use to test? Running on server 2012 on python 27 (I think).

**Comment by Miserlou** [comment]
Possible that functionality doesn't work on Windows, it's untested. The
code is there though, works fine for me on OSX.

**Comment by ThaMunsta** [comment]
Possibly. The only part of the setup that failed was requests[security]>=2.9.0 but it looks like mutagen is there and working. Not a huge deal everything else works perfect

**Comment by cactimurray** [comment]
Yeah I think it's definitely a Windows thing, I haven't looked into it yet but my Windows machine won't add any ID3 information including covers. Mac works perfectly.

**Comment by Evolution0** [comment]
Some of the imports are flagged as unresolved references in soundscrape (APIC, WXXX) for me under windows.

I've noticed personally that some of the imports are not what you would expect them to be between versions,

**Comment by riwale** [comment]
I'd too like to know about this, as i miss the album art quite a lot :)

I'm using soundscrape in linux, will post a fix if noone fixes this anytime soon ;)

**Comment by ThaMunsta** [comment]
@riwale It's not an issue with clients reading the tags, it seems to be an issue with tags being saved into the files when scoundscrape is running on windows.
I have two ways of downloading from soundcloud on my windows server. I prefer soundscrape because I was automating this via command line. I can download the same song my two different ways but soundscrape doesn't grab the cover art.
