### ISSUE TITLE
Will deepelmdigital.com be supporting?

### ISSUE THREAD

**Issue by becauseim** [Miserlou/SoundScrape#144]
Will deepelmdigital.com like a bandcamp.com be supporting? [The link fo the example](http://deepelmdigital.com/album/tall-tales).

**Comment by brachna** [comment]
That's a bandcamp page.
Just run such a page with -b flag.

**Comment by becauseim** [comment]
Yes, true. Thank you! Will be  any other sites adding later?

**Comment by brachna** [comment]
Not that I'm aware of, that's up to Miserlou.

**Comment by Miserlou** [comment]
Don't quite understand the question. Next target would be download gates.
