### ISSUE TITLE
Non-ASCII characters

### ISSUE THREAD

**Issue by ThaMunsta** [Miserlou/SoundScrape#149]
Is it possible to have this work with special characters? Even if it can simply filter them out when saving the file.

**Comment by Miserlou** [comment]
Are you on Windows, perchance? I thought I was done with this unicode nightmare.

**Comment by brachna** [comment]
What exactly do you mean? Special characters like :*^?

**Comment by ThaMunsta** [comment]
AHH yes it was fixed last month. Just pulled the new code and it's working now 👍
