### ISSUE TITLE
Soundscrape chokes on WAV files

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/SoundScrape#15]
I didn't know that WAVs were even available on SoundCloud, but apparently so, and they break SoundScrape:

https://soundcloud.com/woolymammothmusic/woolymammoth-ella

$ soundscrape https://soundcloud.com/woolymammothmusic/woolymammoth-ella
Downloading: † ELLA †
[################################] 41817/41817 - 00:00:00
can't sync to an MPEG frame

**Comment by eedeep** [comment]
Bump

**Comment by Miserlou** [comment]
Yeahhhh..

**Comment by tyhallcsu** [comment]
I don't even get the "can't sync" error with this one...
`$ soundscrape https://soundcloud.com/woolymammothmusic/woolymammoth-ella
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/soundscrape/soundscrape.py", line 77, in main
    process_soundcloud(vargs)
  File "/usr/local/lib/python2.7/dist-packages/soundscrape/soundscrape.py", line 121, in process_soundcloud
    response = requests.get(streams_url).json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by Miserlou** [comment]
The track has been removed from Soundcloud: https://soundcloud.com/woolymammothmusic/woolymammoth-ella

**Comment by tyhallcsu** [comment]
Ah, well I found a song with the same issue, then:
`$ soundscrape https://soundcloud.com/marty-grimes-music/die-for-me-feat-kyle-christoph-andersson`

```
Downloading: Die For Me (feat. KYLE & Christoph Andersson)
[################################] 9321/9321 - 00:00:04
can't sync to an MPEG frame
```

**Comment by tyhallcsu** [comment]
What's interesting, is regardless of the "can't sync to an MPEG frame" error that was thrown, the file seems to play just fine. Link: https://soundcloud.com/marty-grimes-music/die-for-me-feat-kyle-christoph-andersson

**Comment by Miserlou** [comment]
This may actually be a Mutagen error, or at least in our unspecified handling of Mutagen errors.

**Comment by Miserlou** [comment]
Works for Wavs now, but not M4As

**Comment by tyhallcsu** [comment]
Bump -- has this made any development progress?
