### ISSUE TITLE
How do i download multiple tracks at once ?

### ISSUE THREAD

**Issue by grohit19** [Miserlou/SoundScrape#152]
Like we have an option in wget , we can put all URLs in once text file and we can do
 `wget -i <filename>.txt
`
I have like 20 SC tracks, tried to do it in the same way, of course, it didn't work and later had to do it one by one manually for few.
For rest, I just wrote - 

```
Soundscrape <url>
Soundscrape <url>
Soundscrape <url>
....
Soundscrape <url>
```

and watched it DL all tracks.

Any alternate way?

**Comment by Miserlou** [comment]
This is an interesting question!

Here are the answers from stack: http://unix.stackexchange.com/questions/149726/how-to-pass-each-line-of-a-text-file-as-an-argument-to-a-command

I think this should actually be a unix command itself..

**Comment by Miserlou** [comment]
Aaaand of course it is already. http://www.gnu.org/software/parallel/
