### ISSUE TITLE
Unable to download from Mix cloud

### ISSUE THREAD

**Issue by grohit19** [Miserlou/SoundScrape#154]
D:\Google Drive Folder\MyMusic_G_Drive\English\Johnny Monsoon>soundscrape http:/
/www.mixcloud.com/johnnymonsoon/the-sound-of-trance-episode-27-set-from-above-be
yond-show/
Active code page: 65001
Downloading: Johnny Monsoon - The Sound of Trance Episode 27 Set from Above &amp
; Beyond Show (rl]])
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\Scripts\soundscrape-script.py", line
9, in <module>
    load_entry_point('soundscrape==0.29.4', 'console_scripts', 'soundscrape')()
  File "c:\program files (x86)\python35-32\lib\site-packages\soundscrape\soundsc
rape.py", line 107, in main
    process_mixcloud(vargs)
  File "c:\program files (x86)\python35-32\lib\site-packages\soundscrape\soundsc
rape.py", line 712, in process_mixcloud
    filenames = scrape_mixcloud_url(mc_url, num_tracks=vargs['num_tracks'], fold
ers=vargs['folders'], custom_path=vargs['path'])
  File "c:\program files (x86)\python35-32\lib\site-packages\soundscrape\soundsc
rape.py", line 753, in scrape_mixcloud_url
    download_file(data['mp3_url'], track_filename)
  File "c:\program files (x86)\python35-32\lib\site-packages\soundscrape\soundsc
rape.py", line 1038, in download_file
    r = requests.get(url, stream=True)
  File "c:\program files (x86)\python35-32\lib\site-packages\requests\api.py", l
ine 70, in get
    return request('get', url, params=params, **kwargs)
  File "c:\program files (x86)\python35-32\lib\site-packages\requests\api.py", l
ine 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\program files (x86)\python35-32\lib\site-packages\requests\sessions.p
y", line 474, in request
    prep = self.prepare_request(req)
  File "c:\program files (x86)\python35-32\lib\site-packages\requests\sessions.p
y", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "c:\program files (x86)\python35-32\lib\site-packages\requests\models.py"
, line 302, in prepare
    self.prepare_url(url, params)
  File "c:\program files (x86)\python35-32\lib\site-packages\requests\models.py"
, line 366, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '[[player.waveformUrl]]': No sche
ma supplied. Perhaps you meant http://[[player.waveformUrl]]?

**Comment by Miserlou** [comment]
Confirming. Looks like they've updated something and our scraper broke.

https://www.mixcloud.com/johnnymonsoon/the-sound-of-trance-episode-27-set-from-above-beyond-show/

**Comment by grohit19** [comment]
Oh no !!! :( that's a sad thing to hear. Any possibilities this will be fixed by you in near future :/

**Comment by Miserlou** [comment]
For sure, but I think it might be @brachna who fixes it! :-)

**Comment by brachna** [comment]
I'm busy making support for a site that nobody needs lol

**Comment by grohit19** [comment]
@brachna No buddy !! don't say like that... you never know who would need it .. :smiley_cat: and I am a huge fan of Johnny monsoon... the only place where I see all his old podcast is at mixcloud :musical_note: .... and @Miserlou all other online sites too unable to pull request which used to fetch the mp3 directly from the url.... looks like mix cloud backend folks really did some great job... hmmmm

**Comment by injectedfusion** [comment]
Just wanted to say many thanks for all the work you guys put into this.
Your efforts are appreciated.

**Comment by Miserlou** [comment]
Thanks. 

This shouldn't actually too hard to update the scraper, they've just switched to using the anglular frontend framework for their templating, which actually should mean that there's a handy blob of JSON for us to read somewhere..

**Comment by grohit19** [comment]
Yes , I do agree :100: % with @injectedfusion ...

**Comment by grohit19** [comment]
@Miserlou You are awesome !! :+1:

**Comment by Miserlou** [comment]
So much for nice friendly blob of JSON - try loads and loads of obfuscated JavaScript garbage.. >:[

**Comment by Miserlou** [comment]
Actually never mind, that was easier than it was before. Running test now..

**Comment by Miserlou** [comment]
Can you guys try master branch? Works for me but getting 403s from Travis :[

**Comment by Evolution0** [comment]
Testing it now. Just realized how incredibly slow downloading from mixcloud is. (Though it is a 53 minute file)

Edit: Seems to be working correctly.

**Comment by grohit19** [comment]
@Miserlou @Evolution0 - I jus woke up. Let me test it now. *excited* 😀

**Comment by Evolution0** [comment]
Weird, worked for me though it took what seemed ages to download.

**Comment by grohit19** [comment]
@Evolution0 could you paste the code and show. I'm getting the same errors as I posted in my first comment box 😖😫

**Comment by Evolution0** [comment]
You grabbed the master branch and didn't install via pip right? I doubt @Miserlou would push out a new release for one modification.

**Comment by Miserlou** [comment]
No, this is now published to 0.29.5 on pip, so you can pip install soundscrape --upgrade to use it..

**Comment by grohit19** [comment]
@Miserlou thanks a lot man !!!! :+1: you are awesome :smiley_cat:

**Comment by grohit19** [comment]
Just to let you know, its working now however,  taking hell lot of time to DL :disappointed:
