### ISSUE TITLE
Header encoding

### ISSUE THREAD

**Issue by Evolution0** [Miserlou/SoundScrape#159]
I just ran into this myself with bandcamp-dl and thought that possibly you would have encountered this issue by now and fixed it (So I could snatch your code ;) turns out nope its broken for both our projects.

This is specific to requesting headers and happens due to requesting `content-length` on a UTF-8 header (Which httplib can't handle prior to Python 3.6.0)

On Python 3.6.0 everything is fine, here is a URL for testing purposes:
https://blankbanshee.bandcamp.com/album/blank-banshee-1

It will reach the forth track, silently fail to get `content-length` then go into what seems to be an infinite loop in soundscrapes case.

The specific error message after adding some logging (Should be the same for soundscrape):
```
WARNING:requests.packages.urllib3.connectionpool:Failed to parse headers (url=http://p4.bcbits.com:80/download/track/21159a4155f4e48bdcd6bad6f52f6bd2/mp3-128/3526805659?fsig=8fddc2048869237b5f26ffcb8e9269ab&id=3526805659&stream=1&ts=1485504000.0&token=1485504060_59f55c1ef90014570e72dee8f2b1d2a462a7ab3c): [MissingHeaderBodySeparatorDefect()], unparsed data: 'جس�\x85�\x87 ساز�\x8c �\x85�\x87تاب.mp3"; filename*=UTF-8\'\'Blank%20Banshee%20-%20Java%20Clouds-%D9%85%D8%AC%D8%B3%D9%85%D9%87%20%D8%B3%D8%A7%D8%B2%DB%8C%20%D9%85%D9%87%D8%AA%D8%A7%D8%A8.mp3\r\nCache-Control: max-age=0, proxy-revalidate\r\nETag: "57fb26cc-210c86"\r\nLast-Modified: Mon, 10 Oct 2016 05:27:39 GMT\r\nX-BC-Host: izac\r\nX-Content-Duration: 132.159\r\nVia: 1.1 varnish\r\nFastly-Debug-Digest: acdc8c5b7f038cbd057118afe7d16455b15b1de5dc4565ac0be33e10f9a2916e\r\nContent-Length: 2165894\r\nAccept-Ranges: bytes\r\nDate: Fri, 27 Jan 2017 07:05:50 GMT\r\nVia: 1.1 varnish\r\nAge: 3257080\r\nConnection: keep-alive\r\nX-Served-By: cache-dfw1833-DFW, cache-jfk8145-JFK\r\nX-Cache: HIT, HIT\r\nX-Cache-Hits: 1, 1\r\nX-Timer: S1485500750.573681,VS0,VE0\r\n\r\n'
Traceback (most recent call last):
  File "C:\Users\Anthony\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 403, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "C:\Users\Anthony\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\util\response.py", line 66, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
requests.packages.urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'جس�\x85�\x87 ساز�\x8c �\x85�\x87تاب.mp3"; filename*=UTF-8\'\'Blank%20Banshee%20-%20Java%20Clouds-%D9%85%D8%AC%D8%B3%D9%85%D9%87%20%D8%B3%D8%A7%D8%B2%DB%8C%20%D9%85%D9%87%D8%AA%D8%A7%D8%A8.mp3\r\nCache-Control: max-age=0, proxy-revalidate\r\nETag: "57fb26cc-210c86"\r\nLast-Modified: Mon, 10 Oct 2016 05:27:39 GMT\r\nX-BC-Host: izac\r\nX-Content-Duration: 132.159\r\nVia: 1.1 varnish\r\nFastly-Debug-Digest: acdc8c5b7f038cbd057118afe7d16455b15b1de5dc4565ac0be33e10f9a2916e\r\nContent-Length: 2165894\r\nAccept-Ranges: bytes\r\nDate: Fri, 27 Jan 2017 07:05:50 GMT\r\nVia: 1.1 varnish\r\nAge: 3257080\r\nConnection: keep-alive\r\nX-Served-By: cache-dfw1833-DFW, cache-jfk8145-JFK\r\nX-Cache: HIT, HIT\r\nX-Cache-Hits: 1, 1\r\nX-Timer: S1485500750.573681,VS0,VE0\r\n\r\n'
```

This *should be harmless* as others around the net have mentioned when I look but it seems Requests doesn't like it in particular and fails entirely.

A workaround was posted in a [Requests issue here](https://github.com/kennethreitz/requests/issues/3098#issuecomment-255919248).

**Comment by Miserlou** [comment]
Can't reproduce, that test URL downloaded just fine for me. It is very a e s t h e t i c.

**Comment by Miserlou** [comment]
Dang this is actually a pretty cool album, thanks for the tip.

**Comment by Evolution0** [comment]
Did you test running soundscrape under Python 3.5.2 and under?

**Comment by Miserlou** [comment]
2.7 OSX

That is a seriously nutso error dang

**Comment by Evolution0** [comment]
Yeah I was reading through the Requests issue again and it seems its an error that happens under Python 3 but doesn't effect the latest release (3.6.0) anything in between will get it if the header is utf-8.  

Its a real pain as at first it seems the warning can be ignored and files downloaded without grabbing content-length (though no loading bar or file integrity checking in that case) but something happens in the background that puts it into an infinite loop.  

I sat in debug for a good 10 minutes just stepping though the download iterator and it went on and on without end (But the file remained the same size) even trying to just drop the entire content into a file without iterating doesn't help.

**Comment by brachna** [comment]
`https://blankbanshee.bandcamp.com/album/blank-banshee-1`
Downloads fine here: Windows 8.1 x64, Python 3.5.2 x64, latest Soundscrape.
Nonetheless it's serious if any of supported versions is affected.

**Comment by SimplicityGuy** [comment]
Seems like a random issue that isn't reproduced or was in requests at some point.
