### ISSUE TITLE
Encode MP3 at 320kb/s instead of 128 kb/s

### ISSUE THREAD

**Issue by dallen4** [Miserlou/SoundScrape#162]
When you download a track it is always downloaded as 128kb/s (one of the lowest average quality bit rates for an MP3 file). There should be functionality to support at least trying to download a track at 320kb/s before resorting to 128kb/s. I've been looking into it, but not sure which module it is dependent on.

**Comment by Miserlou** [comment]
If possible, it will prefer 320s when they're available. You can force this behavior with `-d`. Reopen if this isn't actually the case.

**Comment by dallen4** [comment]
Actually, after further research, I found that even with forcing the behavior with `-d`, you won't get better than a 128kbs track from SoundCloud because the api resource link you use to download the file is the stream_url and according to their API that URL only returns 128kbs.
![soundcloud api](https://cloud.githubusercontent.com/assets/9330816/22480566/71c384be-e7b7-11e6-8577-0893c53cca38.png)

**Comment by Miserlou** [comment]
The 320s come from the Download links

**Comment by dallen4** [comment]
Can you still rip the 320s from the Download links when the track isn't available for download?

**Comment by Miserlou** [comment]
No
