### ISSUE TITLE
How do I install it besides that piece of code

### ISSUE THREAD

**Issue by DwarfmanDDH** [Miserlou/SoundScrape#168]
I have tried in PowerShell as well with opening setup.py but I can't seem to figure it out.

**Comment by Evolution0** [comment]
SoundScrape is written in and uses Python libraries, you need to first install a supported Python version then use pip to install SoundScrape itself as it says [here](https://github.com/Miserlou/SoundScrape#usage) pip can be run in CMD after installing Python*, if pip turns up as an invalid command re-log into your user account in windows as your PATH may not have updated.

*When installing Python if given the option to add it to the PATH environment variable check it and allow it to.

**Comment by SimplicityGuy** [comment]
Unrelated to the tool. This tool requires Python to be installed. Please follow Python installation instructions for your platform.
