### ISSUE TITLE
No ID3 tags?

### ISSUE THREAD

**Issue by ZoeFiri** [Miserlou/SoundScrape#170]
Everything seems to be working, except I don't get any ID3 tags... Do I need to use an extra command?

**Comment by Pyrall** [comment]
Ok, it turns out that I was actually getting the tags, but I still can't get artwork.

**Comment by Evolution0** [comment]
Would probably help @Miserlou if you noted which site you were attempting to get tracks from and the URL to said tracks.

**Comment by SimplicityGuy** [comment]
Odd, I see art work on tracks. Without a specific repro for this issue, it's nearly impossible to see what's not working.
