### ISSUE TITLE
Is there a limit on how many songs i can download?

### ISSUE THREAD

**Issue by MarcusEdward** [Miserlou/SoundScrape#172]
I tried to download all songs of [this user](https://soundcloud.com/nocopyrightsounds), but it stopped after 200 songs. I already upgraded the program and retried many times but still got the same result. What did I do wrong?

**Comment by mavieth** [comment]
Had the same issue. It stopped after 49 songs for j-scinta/sets/spotify-songs-1.

**Comment by the-nick-dev** [comment]
Same issue for https://soundcloud.com/officialpandaeyes - downloaded first 41 tracks, not further down

**Comment by SimplicityGuy** [comment]
SoundScrape is not doing anything to prevent downloads. These may be coming from SoundCloud or one of the other sources.
