### ISSUE TITLE
Mixcloud - list index out of range 

### ISSUE THREAD

**Issue by pyrgns** [Miserlou/SoundScrape#176]
I'm having trouble downloading something from mixcloud. Soundcloud works fine. Thanks for the great work regardless

$ soundscrape https://www.mixcloud.com/NTSRadio/melon-magic-3rd-may-2017/ -of
Problem downloading https://www.mixcloud.com/NTSRadio/melon-magic-3rd-may-2017/
list index out of range

**Comment by pyrgns** [comment]
it might have been that file because other ones are working. closing

**Comment by 2ge** [comment]
I got same error:
```
$ soundscrape https://www.mixcloud.com/ReggaeRevolutionRadioShow/
Problem downloading https://www.mixcloud.com/ReggaeRevolutionRadioShow/
list index out of range

$ soundscrape -v
0.30.1
```

**Comment by lostfictions** [comment]
Having this problem for this url: https://www.mixcloud.com/DBGO/%E3%83%97%E3%83%A9%E3%82%B9%E3%83%81%E3%83%83%E3%82%AF%E3%81%AE%E6%84%9B-plastic-love/

**Comment by FlorianHeigl** [comment]
same here, for quite a few. can you give some advice how to debug, i can't dig into the whole application, but is there a most likely spot to look at?
