### ISSUE TITLE
Not able to download:

### ISSUE THREAD

**Issue by SaintFenix** [Miserlou/SoundScrape#184]
It seems the vast majority of songs I try to download just return a failure to download. simply stating: Problem downloading SONG.

I have ran the built in updater to no success.

no real idea what's going on, was downloading fine up until recently.

**Comment by EmilFrom** [comment]
I'm having exactly the same problem. Just installed the app.
The idea seems so cool. Hope it gets updated.

**Comment by SimplicityGuy** [comment]
Unfortunately, as filed, this issue doesn't have enough detail to be useful. SoundScrape does not guarantee that content can be downloaded. It tries to download the content using the API. But there are many things here that can go wrong: (1) the content is region locked, (2) the content is private and not downloadable, (3) issues with SoundCloud [there are many], (4) and many other issues. What has been done in the tool is to make it a bit more robust against failures.
