### ISSUE TITLE
Running python soundscrape rabbit-i-am returns exception

### ISSUE THREAD

**Issue by jzhanglsw** [Miserlou/SoundScrape#189]
The exception says "can't find '__main__' module in 'soundscrape

**Comment by Miserlou** [comment]
System? Python version?

**Comment by Miserlou** [comment]
Also they took their tracks down. :(

**Comment by jzhanglsw** [comment]
I'm running this on a 64bit Windows 10 Enterprise
I'm running it on Python 3.6.2
I tried it with other artists on soundcloud

**Comment by Miserlou** [comment]
They don't have any tracks any more, that's probably why:
https://soundcloud.com/rabbit-i-am/tracks

**Comment by jzhanglsw** [comment]
I just tried it with chillchildren
They definitely have tracks:
https://soundcloud.com/chillchildren/tracks

**Comment by jzhanglsw** [comment]
Running the test file works though. So I find that very odd...

**Comment by SimplicityGuy** [comment]
Doesn't look to be an issue any longer.
