### ISSUE TITLE
limited number of tracks downloaded

### ISSUE THREAD

**Issue by a7medo778** [Miserlou/SoundScrape#193]
hi guys
i am scrapping a channel with a 1000 tracks, the downloader quits after 109, i tried running it again but show that everything is downloaded and quit again
scdl finds and starts downloading all 1000, but the naming thingy makes me need soundscrape

so whats the solution ?

**Comment by the-nick-dev** [comment]
had before, not anymore

**Comment by SimplicityGuy** [comment]
I've had this happen too. There is nothing in SoundScrape that causes this. This typically is something on the SoundCloud side where the slow connectivity to an IP or restrict it for a short period of time.
