### ISSUE TITLE
i cant download anything and cant upgrade

### ISSUE THREAD

**Issue by Zibbk** [Miserlou/SoundScrape#195]
![hata](https://user-images.githubusercontent.com/17888239/29931208-39a540ae-8e79-11e7-9c57-35e884845fdf.png)

this pic shows why i cant upgrade and i dont know why. 

when i try the download albums or something just see "Active code page: 65001" but nothing happen

**Comment by jjp1023** [comment]
The upgrade can be done using elevated permission. But running into 
```
sudo pip3 install soundscrape --upgrade
```

But unable to download anything:
```bash
soundscrape https://www.mixcloud.com/directmusicservice/dms-mini-mix-week-273-dj-dirty-darren/
Problem downloading https://www.mixcloud.com/directmusicservice/dms-mini-mix-week-273-dj-dirty-darren/
list index out of range
```

**Comment by Zibbk** [comment]
im using w10 and bandcamp is not working

**Comment by jjp1023** [comment]
Try running cmd as an admin.  maybe that will help.

**Comment by Zibbk** [comment]
still not working.

showin just "Active code page: 65001"

**Comment by Zibbk** [comment]
oh now its working, thanks for your help

**Comment by jjp1023** [comment]
yups no problem. For mixcloud, looks like they change the stream api.  So i dont know if its going to be a simple fix or not.

**Comment by denisaraujo** [comment]
Hello, i'm not able to run soundscrape command. It seems it's not installing. Any tips?
Thanks
<img width="1249" alt="screen shot 2017-10-06 at 09 03 05" src="https://user-images.githubusercontent.com/464969/31277027-4147684c-aa75-11e7-8326-43209faf446a.png">

**Comment by jjp1023** [comment]
Try this: sudo pip install soundscrape --upgrade
If your default is python3 then try: sudo pip3 install soundscrape --upgrade

**Comment by denisaraujo** [comment]
Hello!! I already did the upgrade and both commands returned this message. :(

**Comment by jjp1023** [comment]
@denisaraujo  Did you use sudo to install? it seems like **pip** is having permission issue. Also if you have python3 installed then try **pip3**.  The errors mean you are not able to uninstall and update the dependecies, so soundscrape never gets installed. 
```
sudo pip install soundscrape
```

**Comment by denisaraujo** [comment]
Yes, i used sudo. :(
Maybe a Sierra problem?

**Comment by jjp1023** [comment]
No I rub Sierra. And I installed successfully. Umm what about pip3?  I remember running into issues with Python 2.7. try installing python3 or higher

**Comment by denisaraujo** [comment]
Yes, that solved the problem!!
Thanks @jjp1023!!!

**Comment by SimplicityGuy** [comment]
MixCloud support was entirely experimental. Prior to starting on PR #241, it was entirely broken, so support for MixCloud was pulled. Adding support back for MixCloud is a large undertaking.
