### ISSUE TITLE
Bandcamp Downloads

### ISSUE THREAD

**Issue by ssurfong** [Miserlou/SoundScrape#196]
Apologies if I missed it somewhere previously, but is there no way to download music from Bandcamp at a higher bitrate of 128k? I am new to using SoundScrape, but I typed in "soundscrape URL OF BANDCAMP ALBUM HERE -d" and it always gives me 128k. I was hoping there is a way to get 320k or even FLAC...

Thank you for your time.

**Comment by brachna** [comment]
no, only 128k

**Comment by Evolution0** [comment]
As @brachna said no. There is a very simple reason for this, the source with which the track is retrieved from is the same as the track preview on the page which is only in 128k; to get higher quality audio you would need to support the artist and pay for the track/album in question, many artists provide both 320k and FLAC in that case.

There is no way to circumvent this limitation and I doubt anyone would be willing to try (At least I would hope)
