### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by justinTM** [Miserlou/SoundScrape#199]
Hi there,

I am using Mac OSX El Capitan. Python version 2.7
I downloaded pip using the `get-pip.py` method, then later uninstalled and reinstalled using `easy_install pip`.

Now, when trying 'sudo pip install soundscrape` (and other variations like using the `-H` flag, the `--upgrade` flag, etc.) I receive this error:

```
No files/directories in /private/tmp/pip-build-5Fb2Po/soundscrape/pip-egg-info (from PKG-INFO)
```

and I KEEP getting it no matter what I try. I've uninstalled pip, uninstalled Python, and I'm stuck! Help :)

**Comment by ChristianKrausse** [comment]
Likely same issue, opened requirements.txt installed manually all requirements via pip and after this,  pip install soundscrape worked. As well as downloads are working.

**Comment by NET-OF-BEING** [comment]
i recommend uninstalling pip and reinstalling it using brew install pip. Then pip install soundscrape.

**Comment by ChristianKrausse** [comment]
It worked after I installed all the requirements , I thought the requirements should be installed by default. So my comment was more helpful for people who did not have the  requirements  as they are in the requirements.txt :)

**Comment by SimplicityGuy** [comment]
This seems unrelated to SoundScrape.
