### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by gilha** [Miserlou/SoundScrape#202]
Works perfectly from my Win10 laptop. 
Tried to use it on my Win7 computer and this error popped up:

![soundscrape_permissionerror](https://user-images.githubusercontent.com/18117093/33626171-74302cdc-da02-11e7-856b-255514839fb6.JPG)

How can I fix this?

Thank you very much!
Gil.

**Comment by bourdeau** [comment]
It's seems to be more of a Windows error rather than a problem with the lib itself. Try to download on another hdd (like usb or whatever)

**Comment by ArielM777** [comment]
This might happen on windows, but it's really a permission error. This happens when the tracks have weird symbols in their name.
In this case, track number 4 has hebrew characters:
`4. | ערפל 04:38`

**Comment by dseptem** [comment]
This might happen on windows, but it's not really a permission error. This happens when the tracks have weird symbols in their name.
In this case, track number 4 has hebrew characters:
`4. | ערפל 04:38`

Funny thing, Python 3.5 soundscrape doesn't encounter this issue.

**Comment by SimplicityGuy** [comment]
Since there's a PR for this (#232), going to close this out.
