### ISSUE TITLE
id3tag-coverart | not original size (substantially smaller)

### ISSUE THREAD

**Issue by fohrums** [Miserlou/SoundScrape#21]
I primarily liked youtube-dl for it's parameters, but <b>SoundScrape seems to do a fantastic job with handling SoundCloud's horrendous errors</b> that I can't even recall the last time I didn't have one when playing <i>any</i> track.

By default SoundScrape works the best. With options like:
<code>auto-tag</code> (depending how the track is titled on-page)
<code>embedcoverart</code> 

+1 for not having to also download the image file but instead embeds it during the downloading process. So all you have is just the track. 
+1 for having it work with e-mail notification links as well.

Everybody is happy now, except....

PROBLEM
-
The coverart that's embeded to the downloaded track isn't the same size as the original trackart.

NOTE
-
again, SoundScrape doesn't offer any <i>parameters</i> and works best by default so isn't there a way to control this?

**Comment by Miserlou** [comment]
I too would prefer to have high resolution cover art, but as far as I can tell, the SC API only returns a low-resolution image for the cover art. However, it could be possible to scrape it from the page and then fall back on the API if that fails. There may also be a way to add a predictable suffix to a path to get the high resolution version - ala https://i1.sndcdn.com/artworks-000098320240-xiw1hm-t500x500.jpg

Do you want to look into this? I'm happy to accept pull requests and ideas.

The art from Bandcamp scrapes should be full enough resolution.

**Comment by Miserlou** [comment]
Okay! I've fixed this in 0.15.1. You should be able to pip install soundscrape --upgrade and have it work with big artwork.

Turns out you can just replace '-large' with '-t500x500' to get the big artwork.

I fixed and published this change in the time it takes to boil a single kettles worth of tea. Woo!
