### ISSUE TITLE
Suggestion: API key cycling

### ISSUE THREAD

**Issue by GillesJ** [Miserlou/SoundScrape#211]
Soundscrape has been hitting the rate limits quickly for some time now.
Maybe it is time to implement API key cycling? Implementation would be fairly simple: in exception handling on a "rate limit reached" response we would cycle to the next key.

Issues to consider:
1. We would need some keys to use. I don't think this will be a problem.
2. Scraping is prohibited by General Prohibitions iv. of their [API Terms of Use](https://developers.soundcloud.com/docs/api/terms-of-use#general). Implementing key cycling might put a target on Soundscrape's back if it enables large rate hits.

**Comment by SimplicityGuy** [comment]
I've been thinking of adding the ability to provide your own API keys either through a settings file or through the command line. This way any user can use their own keys if you have them. It also seems that SoundCloud has stopped allowing users to request new keys. In any case, clearly some keys previously issued still work. Allowing user-provided API keys will be added at some point.

As far as the issues you listed, many podcasting applications, including Apple Podcasts, pull content from SoundClound, including allowing to grab back catalog of items.
