### ISSUE TITLE
soundscrape: command not found

### ISSUE THREAD

**Issue by luiandresgonzalez** [Miserlou/SoundScrape#212]
I`ve followed the instructions for downloading and installing through pip install and it all went fine without errors, but when issuing the command it didin't work. I'm using Ubuntu 18.04 with both pythons installed (2.7 and 3.6.5).

**Comment by codydbgt** [comment]
same

**Comment by promitheus7** [comment]
same

**Comment by promitheus7** [comment]
Let's diagnose - does everyone with this issue use `brew` as their python installation manager?

**Comment by promitheus7** [comment]
Update: I've found out how to resolve the issue on Mac OS Catalina

With the latest Catalina update, by default the `pip3` installation of `soundscrape` isn't able to create the `soundscrape` command to call in the command line. This is due to how permissions are set up with the latest Mac OS. In order to work around this,

- uninstall `soundscrape`
- go to System Preferences -> Security & Privacy -> Privacy -> Full Disk Access
- add your terminal (`Terminal.app`, `iTerm2.app`, etc.) to the list of programs with full disk access
- if that program is open, restart it to enable the new permissions to take affect
- install `soundscrape`

The soundscrape command should now be found and no longer produce the `not found` error.

**Comment by alstergee** [comment]
> Let's diagnose - does everyone with this issue use `brew` as their python installation manager?
> 
> I did some digging - copying the script from the pip3 package and running it manually using `python3` works fine. It's trying to run `soundscrape` from the command line that specifically doesn't work.
> 
> I use a `brew`-managed installation of Python 3, and didn't have this issue before Catalina, which leads me to believe the issue is rooted in the fact that Catalina comes with its own version of `python3` and `pip3`, which may interfere with the `brew` installation.
> 
> I'll continue digging and post any updates here.

can anyone speak english for those of us in the back that dont speak nerd? im running ubuntu what is the 1st step for "copying the script from the pip3 package and running it manually using `python3` works fine"
like an exact command to get this running would be super helpful

**Comment by SimplicityGuy** [comment]
The issue reported here is not one specific to SoundScrape.

On Ubuntu if you have both Python 2.7 and 3.6.5 installed, make sure you're using pip associated with the right Python distribution. For instance, pip3 will be the right alias for the Python 3.6.5 distribution. Additionally, when installing Python packages, you need to run `sudo pip3 install ...`. 

On macOS, please use brew to install Python. There are many great examples of using brew out there. The current version of Python that brew will install is Python 3.8.4. When you pip install, please make sure you're using the version of pip associated with the right distribution of Python. If you've upgrade Python recently using `brew upgrade`, you'll likely need to reinstall all packages as they need to be reparented to the upgraded path.

Some useful commands, on macOS Catalina, but this will work on Ubuntu, Debian, CentOS, etc.
```bash
➜  ~ which python
/usr/bin/python
➜  ~ python --version
Python 2.7.16
```
This is the system Python. Notice, it's Python 2.7.16.

```bash
➜  ~ which python3
/usr/local/bin/python3
➜  ~ python3 --version
Python 3.8.4
➜  ~ which pip
/usr/local/bin/pip
➜  ~ which pip3
/usr/local/bin/pip3
```
This is the version of Python installed by brew. Notice, it's Python 3.8.4. Also notice that both pip and pip3 are aliased to work with the version of Python installed by brew.
