### ISSUE TITLE
Mixcloud - list index out of range

### ISSUE THREAD

**Issue by festerdublin** [Miserlou/SoundScrape#215]
I know its not offically supported.. however thought I would report it anyway.. Tried a few locations.. all hitting the same index out of range

C:\Python27\Scripts>soundscrape.exe https://www.mixcloud.com/SisterBlissOfficial/sister-bliss-in-session-27-10-15/
Active code page: 65001
Problem downloading https://www.mixcloud.com/SisterBlissOfficial/sister-bliss-in-session-27-10-15/
list index out of range

**Comment by aarsakian** [comment]
Did a little bit of research on this, its seems that mixcloud has changed its html structure, "m-preview" no more exists and hence the error.

**Comment by SBKch** [comment]
Confirming - I have the same problem:
soundscrape https://www.mixcloud.com/corenewsuploads/flume-essential-mix-2015-10-03/ -of
Problem downloading https://www.mixcloud.com/corenewsuploads/flume-essential-mix-2015-10-03/
list index out of range

**Comment by jbenz** [comment]
> list index out of range

same issue as well..

**Comment by guysoft** [comment]
Same here, has attempt to fix this been abandoned?

**Comment by w698** [comment]
It seems that it still hasn't been solved

**Comment by w698** [comment]
FFMpeg By slicing

**Comment by SimplicityGuy** [comment]
MixCloud support was entirely experimental. Prior to starting on PR #241, it was entirely broken, so support for MixCloud was pulled. Adding support back for MixCloud is a large undertaking.

**Comment by jamesob** [comment]
@SimplicityGuy do you have a rough estimate of the level of effort required to bring MixCloud support back from the grave? If it's a semi-manageable amount of work, I'd be happy to give it a shot.
