### ISSUE TITLE
Soundscrape doesn't skip wav files that have already been downloaded

### ISSUE THREAD

**Issue by nershman** [Miserlou/SoundScrape#233]
running on OSX downloading likes, I restarted and I noticed it skips all the mp3's which have already been downloaded, but it redownloads wavs instead of skipping them. https://soundcloud.com/numugroup/glvss-methyl-1

**Comment by SimplicityGuy** [comment]
This is fixed in a private fork at the moment, and when #241 is merged, I'll do a PR for that fork.
