### ISSUE TITLE
This song is not downloadable

### ISSUE THREAD

**Issue by nershman** [Miserlou/SoundScrape#234]
AGENT MULDER (THE X FILES) RELEASED is not downloadable.
BILLY COEN (SURVIVAL HORROR Pt1 RELEASED) is not downloadable.
AYA BREA (SURVIVAL HORROR Pt1 RELEASED) is not downloadable.
JOSEPH FROST (SURVIVAL HORROR Pt1) RELEASED is not downloadable.

While trying to download from this set:
https://soundcloud.com/acqualife/sets/post-modern

soundscrape https://soundcloud.com/yung-hentai/angent-mulder
Downloading: AGENT MULDER (THE X FILES) RELEASED
Problem downloading AGENT MULDER (THE X FILES) RELEASED
Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 119, in main
    process_soundcloud(vargs)
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 292, in process_soundcloud
    id3_extras=id3_extras)
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 460, in download_tracks
    puts_safe(e)
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 1315, in puts_safe
    puts(text)
  File "/usr/local/lib/python2.7/site-packages/clint/textui/core.py", line 57, in puts
    s = tsplit(s, NEWLINES)
  File "/usr/local/lib/python2.7/site-packages/clint/utils.py", line 69, in tsplit
    string = string.replace(i, final_delimiter)
AttributeError: 'HTTPError' object has no attribute 'replace'

Maybe it has to do with the username "S?K", since those are the tracks having problems.

**Comment by boardfish** [comment]
Getting this today with a song I was able to download the other day. Error logs read the same. Maybe there's a difference in the SoundCloud API response that this module needs to be updated to cover?

**Comment by boardfish** [comment]
Just tried this against my own artist account and I'm getting the same error.

**Comment by Lanchon** [comment]
FYI...

250+ tracks of the anjunadeep edition set download perfectly, except for this one:
https://soundcloud.com/anjunadeep/the-anjunadeep-edition-241

this one "is not downloadable". been happening for a few months with this particular track.

**Comment by SimplicityGuy** [comment]
SoundScrape tries to download what's reported on SoundCloud. However, there isn't a guarantee it will. This is likely a private track or geo-locked.

**Comment by Lanchon** [comment]
but the point is that it is playable. so why not try ripping the play stream if the download fails?

if fact there should be a way to never try downloading and skip directly to ripping: i may want more compression or just a uniform format across songs.
