### ISSUE TITLE
soundscrape stops downloading after making its way partially through likes

### ISSUE THREAD

**Issue by ericwishom** [Miserlou/SoundScrape#24]
Hi There @Miserlou,

First of all, this is a lifesaver, thank you so much!

Currently running into an issue where soundscrape starts iterating through and downloading all of my liked songs on soundcloud (username is ewish), but the process stops after 50 downloads.  I ran the following commands each time, and they each resulted in soundscrape stopping after 50 downloads.

$ soundscrape ewish -l
$ soundscrape ewish -l -f
$ soundscrape https://soundcloud.com/ewish/likes
$ soundscrape https://soundcloud.com/ewish/likes -f

The 51st song works fine when being downloaded as a track, i.e.
$ soundscrape https://soundcloud.com/ob-obrien/ob-obrien-schemin-up

Just for clarity, wondering if there a limit imposed?  Any way to get around this?

Thanks!

**Comment by Miserlou** [comment]
Ooooooooooh, great catch! Will investigate further. It's likely that the API just returns only the first 50 likes, I'll see what I can do to increase the pagination.

Thank you for reporting this!

**Comment by ericwishom** [comment]
No problem @Miserlou 
Thanks for the followup!

**Comment by ericwishom** [comment]
Hey @Miserlou 
Did you get a chance to check this out? I crawled through the soundcloud docs but couldn't find anything about API limits

**Comment by yeahdef** [comment]
I increased the limit like this and it seems to power through all the files I needed.


    client = soundcloud.Client(client_id=CLIENT_ID)
    if one_track:
        resolved = client.get('/resolve', url=track_url, limit=200)
    else:
        resolved = client.get('/resolve', url=artist_url, limit=200)

    # This is is likely a 'likes' page.
    if not hasattr(resolved, 'kind'):
        tracks = resolved
    else:
        if resolved.kind == 'artist':
            artist = resolved
            artist_id = artist.id
            tracks = client.get('/users/' + str(artist_id) + '/tracks', limit=200)
        elif resolved.kind == 'playlist':
            tracks = resolved.tracks
        elif resolved.kind == 'track':
            tracks = [resolved]
        elif resolved.kind == 'group':
            group = resolved
            group_id = group.id
            tracks = client.get('/groups/' + str(group_id) + '/tracks', limit=200)
        else:
            artist = resolved
            artist_id = artist.id
            tracks = client.get('/users/' + str(artist_id) + '/tracks', limit=200)

**Comment by RobA-M** [comment]
Can anyone confirm whether or not this issue has been resolved in a commit to the repo yet? I am still experiencing this issue.

**Comment by Miserlou** [comment]
This is still open. The limit is raised but pagination isn't there

**Comment by jabui** [comment]
Sorry about all the referenced issues... I'm rather new to Git.
I looked into this, the current API using resolve doesn't seem to work well with 'Likes'.

**Comment by unknownError** [comment]
yes, the issue still persists - only 50 likes downloadable.

**Comment by SimplicityGuy** [comment]
This was resolved by another merge a while ago.
