### ISSUE TITLE
Whats the default download path?

### ISSUE THREAD

**Issue by Darkwolf1515** [Miserlou/SoundScrape#242]
Might sound really stupid, but I have no idea where its downloading the music to.

**Comment by Darkwolf1515** [comment]
Well, I found one of the things that downloaded, in the system 32 folder.

**Comment by shrtcvt** [comment]
any way to change default?

**Comment by SimplicityGuy** [comment]
Yes, you can pass the `-p` or `--path` with a directory that you wish to download to. Also, if you want, you can organize within that directory (or the default directory) based on artist using `-f`.
