### ISSUE TITLE
Got a problem on downloading bandcamp albums

### ISSUE THREAD

**Issue by drisomik** [Miserlou/SoundScrape#246]
hi, I got a problem while downloading bandcamp album.
<img width="575" alt="截屏2020-10-08 上午2 23 09" src="https://user-images.githubusercontent.com/71862088/95372011-8d9c7d00-090d-11eb-9b87-1bcc94030e5b.png">

it is weird that it doesn't have any feedback. but it works well on soundcloud.

**Comment by Miserlou** [comment]
This just started happening to me as well. I haven't looked into it yet, but it's annoying.

**Comment by JDCourtney1969** [comment]
Hi.  I'm just a spectator here - a heavy user of Bandcamp who has used a couple of programs and web sites to convert many Bandcamp tracks to WAV files.   As of about a week ago, I am no longer able to produce large WAV files.   Someone told me it has something to do with "youtube-dl"...?  I am guessing it's a result of some changes made by people at Bandcamp....?     Is anyone else aware of this and has anyone tried to address this?   Either here, or in a different place (pull request?) on this site?   I am very new to this site and am having trouble navigating.  I'm just desperate to get this issue resolved.   Can anyone please help, or tell me where to go to find help?    Thank you!

**Comment by Miserlou** [comment]
This is a different project than youtube-dl, but they're probably experiencing the same thing. I'm guessing BC has updated the structure of their site or API, so we just need to update our scrapers. Takes a few days to get around to it usually.

**Comment by drisomik** [comment]
> This is a different project than youtube-dl, but they're probably experiencing the same thing. I'm guessing BC has updated the structure of their site or API, so we just need to update our scrapers. Takes a few days to get around to it usually.

thank you.

**Comment by RubenArtmann** [comment]
Here is a new scraper: https://github.com/RubenArtmann/bandcamp-dl/blob/main/mod.ts
can't be bothered to port it to python right now, but maybe it can help you. 
Additionally this one hopefully does not break so quick, since it is purely based on grepping urls out of the webpage.

**Comment by banagale** [comment]
@RubenArtmann Been looking for a reason to use deno. Thank you.

**Comment by dm17** [comment]
> Here is a new scraper: https://github.com/RubenArtmann/bandcamp-dl/blob/main/mod.ts
> can't be bothered to port it to python right now, but maybe it can help you.
> Additionally this one hopefully will not break so quickly, since it is purely based on grepping urls out of the webpage.

Tested & works for bandcamp scraping?

**Comment by RubenArtmann** [comment]
> > Here is a new scraper: https://github.com/RubenArtmann/bandcamp-dl/blob/main/mod.ts
> > can't be bothered to port it to python right now, but maybe it can help you.
> > Additionally this one hopefully will not break so quickly, since it is purely based on grepping urls out of the webpage.
> 
> Tested & works for bandcamp scraping?

of course; I would not want to write a scraper that i am not using

**Comment by banagale** [comment]
@RubenArtmann Thanks for this, I also tested it.  Off topic--but I was curious if there are any specific deno resources or communities that you're following. I'd like to sort of track new efforts in this area and was wondering where the pulse of the community is.
