### ISSUE TITLE
Porting to python3

### ISSUE THREAD

**Issue by xHN35RQ** [Miserlou/SoundScrape#28]
Thoughts?

I got soundscrape to launch under Python 3 on [this fork](https://github.com/xHN35RQ/SoundScrape) after making some syntax changes, but it will not download files so I think there are some more changes that need to be made to port it to Python 3. I don't know how long it would take to port.

One reason to port is that people are running into install issues under python3, and having dependency troubles: #5 Moving to python3 would fix these issues and reduce further issues as more and more people move to python3.

If you choose to remain on 2.7 then maybe make a note of that in the readme that it requires 2.7 and how to setup 2.7?

Also, if you don't port to python3 then this change is needed to allow for mutagen 1.29 or greater to fix several install issues I've run into: https://github.com/Miserlou/SoundScrape/pull/27

**Comment by xHN35RQ** [comment]
Ok porting to python3 is a yes (https://github.com/Miserlou/SoundScrape/issues/5#issuecomment-109661021) so I'll investigate further into what changes are necessary.

**Comment by xHN35RQ** [comment]
I ran soundscrape through [the 2to3 fixers](https://docs.python.org/3/library/2to3.html) for starters, it only made 12 changes as you can see here: https://github.com/xHN35RQ/SoundScrape/commit/2d590fe38a847d8f70ebae09b9856b6468ec1d59

As of that commit, running soundscrape under python3 with all requirements updated to latest versions fails to download from soundcloud and simply tells me:

    `Problem downloading b"Name of track to download"`

When I try to download a bandcamp track, I get a different error:

    Problem downloading b'Name of track to download'
    Can't convert 'bytes' object to str implicitly

I'm not sure where the `b` is coming from in the error messages above. The bytes to str error seems to indicate it's a `requests` module error. It's expecting requests2.1.0 however the latest is 2.7.0 and maybe something has changed between those versions to cause the above errors.

**Comment by xHN35RQ** [comment]
Closing because 1) it's not that big of an issue since python2.7 works fine so far, 2) I'm not the right person to port this so I shouldn't be involved and 3) any work on porting will take place elsewhere in the repo.

**Comment by luqmaan** [comment]
http://python3porting.com/problems.html#bytes-strings-and-unicode
