### ISSUE TITLE
invalid mode ('wb') or filename

### ISSUE THREAD

**Issue by L30Bola** [Miserlou/SoundScrape#31]
Got this error and it's caused by using : on file names on Windows. The didn't music have this char on it's name. Got the error when trying to download it alone and when trying to download the full album.

![captura de tela 2015-08-18 05 47 41](https://cloud.githubusercontent.com/assets/10711497/9326005/16f8f98a-456d-11e5-94d0-2c53cb1a257b.png)

**Comment by Miserlou** [comment]
Good bug! :)

**Comment by Miserlou** [comment]
Cannot reproduce on OSX.

**Comment by Miserlou** [comment]
Should be fixed anyway.
