### ISSUE TITLE
Downloading fails on special characters on Soundcloud

### ISSUE THREAD

**Issue by soviel** [Miserlou/SoundScrape#32]
Soundscrape seems to be unable to download soundcloud tracks where there is a ü in the title.

Example: https://soundcloud.com/danielavery/daniel-avery-all-i-need-roman-flugel-remix

I get: Problem downloading Daniel Avery - All I Need (Roman Flügel Remix)

**Comment by Miserlou** [comment]
Cannot reproduce on OSX.

**Comment by nershman** [comment]
I also am having this problem.  Any tracks with emoji, chinese or japanese, or other special unicode characters have a problem downloading on Windows 7.

**Comment by nershman** [comment]
I had the same problem on Windows 7. Tried running on OSX and it worked fine.
