### ISSUE TITLE
--open does not work with bandcamp artists with multiple albums

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/SoundScrape#38]
soundscrape -of https://mrcarmack.bandcamp.com/

Downloading: Strolling
[################################] 4505/4505 - 00:01:10

Traceback (most recent call last):
  File "/usr/local/bin/soundscrape", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 67, in main
    process_bandcamp(vargs)
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 247, in process_bandcamp
    open_files(filenames)
  File "/usr/local/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 621, in open_files
    process = Popen(command, stdout=PIPE, stderr=PIPE)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

**Comment by Miserlou** [comment]
Paging @MasterFocus  :fire:

**Comment by MasterFocus** [comment]
:sweat:
Noted. Will take a look more carefully this weekend.
<sub>I'm right now creating a Pull Request to propose a few more changes to the Bandcamp scraper, but I didn't touch anything related to the _filenames_ variable.</sub>

**Comment by MasterFocus** [comment]
As of 2095f932b554981e51bc0342c0de897f8a4a2dc3, the Bandcamp scraper makes recursive calls when dealing with a /music page. As a consequence, the _filenames_ variable of the _process_bandcamp()_ method contains a list of lists!

:disappointed: My bad. I have found a fix and will commit it before you possibly merge #39.

**Comment by MasterFocus** [comment]
This can probably be closed now.

On a side note, I'm not really a python programmer, so I'm not familiar with certain tools.
I noticed you did fix some formatting after merging #39 and you asked me [**here**](https://github.com/Miserlou/SoundScrape/pull/36#issuecomment-153483714) to use [**pep8ify**](https://pypi.python.org/pypi/pep8ify).
Is that preferred over [**autopep8**](https://pypi.python.org/pypi/autopep8/)?

**Comment by Miserlou** [comment]
Do you have a test case provided for this yet? I'm not sure if it's working or not..

**Comment by Miserlou** [comment]
Hey Master - still finding that Bandcamp opening isn't working properly. :-(

For instance:

soundscrape -of https://braedenbailey.bandcamp.com/track/woo-hah

Downloads, but does not open.

**Comment by MasterFocus** [comment]
I will commit a fix now.
Sorry for the delay. It's been a crazy month and the next 30 days or so will be **extremely** busy for me.
I'll definitely read more about using these tools and creating proper tests in the future. ;)

**Comment by Miserlou** [comment]
I understand, no worries! Looking forward to your fix, I hope this gets you
more involved with contributing to open source software!

Thanks again,

**Comment by Miserlou** [comment]
I believe this is fixed in 0.22.1
