### ISSUE TITLE
Invalid environment marker: python_version >"3.0"

### ISSUE THREAD

**Issue by justinglavin** [Miserlou/SoundScrape#50]
I'm on a fresh Ubuntu install and receiving the following error:

justin@megatron:~$ pip install soundscrape
Collecting soundscrape
  Using cached soundscrape-0.23.5.tar.gz
    Complete output from command python setup.py egg_info:
    Collecting https://bitbucket.org/lazka/mutagen/get/default.tar.gz
      Using cached https://bitbucket.org/lazka/mutagen/get/default.tar.gz
      Requirement already satisfied (use --upgrade to upgrade): mutagen===1.31.-1 from https://bitbucket.org/lazka/mutagen/get/default.tar.gz in /usr/local/lib/python2.7/dist-packages
    warning: pypandoc module not found, could not convert Markdown to RST
    error in soundscrape setup command: Invalid environment marker: python_version < "3.0"
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-b8Pvnk/soundscrape

I was able to get past this same error on my Mac OSX box by installing another python instance using brew. Surely I'm doing something wrong here... but I can't figure it out.

**Comment by Miserlou** [comment]
Hm. Which Ubuntu?

**Comment by justinglavin** [comment]
Ubuntu 14.04.3 LTS 64 Bit. 

As a workaround, I removed this check line from the installer and everything is working great. Thank you for working on this app, it's been a game changer for me :)

**Comment by jamiees2** [comment]
Reinstalling setuptools seemed to fix it for me.

**Comment by lowend** [comment]
hi all, this was the first error in a series for me....

to fix i ran this, and then what I did in the issue I will post below.

pip install pypandoc

sudo pip install -U pip

and then I reinstalled soundscrape using

pip install soundscrape 

and it all worked out :)

many thanks!

**Comment by unknownError** [comment]
I got the same problem on a raspbian and an older ubuntu machine. on the ubuntu machine the above steps mentioned by lowend helped already. on the raspbian machine the pip install of pypandoc didn't work, but sudo apt-get install pandoc helped.

**Comment by samthetechie** [comment]
thanks @unknownError that last tip from you helped me.
Linux darkside 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u1 (2015-12-14) x86_64 GNU/Linux
steps I took to get a working installation: 
sudo pip install -U pip
sudo apt-get install pandoc
sudo pip install soundscrape

**Comment by Miserlou** [comment]
Pandoc shouldn't  be necessary for the install, and neither should sudo.

**Comment by samthetechie** [comment]
On 10/01/16 18:55, Rich Jones wrote:
> Pandoc shouldn't be necessary for the install, and neither should sudo.
> 
> On Sun, Jan 10, 2016 at 6:18 PM, Samuel Carlisle <notifications@github.com>
> wrote:
> 
>> thanks @unknownError <https://github.com/unknownError> that last tip from
>> you helped me.
>> Linux darkside 3.16.0-4-amd64 #1
>> <https://github.com/Miserlou/SoundScrape/issues/1> SMP Debian
>> 3.16.7-ckt20-1+deb8u1 (2015-12-14) x86_64 GNU/Linux
>> steps I took to get a working installation:
>> sudo pip install -U pip
>> sudo apt-get install pandoc
>> sudo pip install soundscrape
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Miserlou/SoundScrape/issues/50#issuecomment-170372302>
>> .
>>
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Miserlou/SoundScrape/issues/50#issuecomment-170374471>.
> 

then remove the dep from the pip. I was getting pandoc not found in path
errors prior to installing it...

-- 
Samuel "samthetechie" Carlisle
https://samthetechie.github.io/
BEng (Hons) Dunelm MIET
PGP Public Key: 54828CAA
9E01 D8A4 CFEB ED72 B0D2
70D7 1D57 A297 5482 8CAA

**Comment by gleitz** [comment]
I was able to fix this with the same solution to #57.

**Comment by fmoraw** [comment]
This worked for me: 

> sudo pip install -U pip wheel setuptools

**Comment by Miserlou** [comment]
This should be fixed in 0.23.6
