### ISSUE TITLE
Track unavailable for scraping

### ISSUE THREAD

**Issue by florensie** [Miserlou/SoundScrape#53]
I tried downloading all music from approachingnirvana from bandcamp but at a certain it gives "Track unavailable for scraping" for every track.

**Comment by Miserlou** [comment]
Works for me. Can you try pip install soundscrape --upgrade

**Comment by florensie** [comment]
When I try to do that I get: error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/share': Operation not permitted
