### ISSUE TITLE
Occasional horrific noise

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/SoundScrape#56]
https://soundcloud.com/kaytranada/lucypearl-dontmesswithmymans-kaytraedit

File is saved an mp3, although when played, results in six seconds of horrific screeching noise.

Assuming this is a relative of https://github.com/Miserlou/SoundScrape/issues/15

**Comment by tyhallcsu** [comment]
Is this still an issue? seems to download and play fine for me!
soundscrape==0.23.10

**Comment by Miserlou** [comment]
Oh, interesting.

It seems that this is actually a bug in iTunes, and not SoundScrape. It plays fine in Preview, but makes digital screaming sounds in iTunes.

**Comment by tyhallcsu** [comment]
Good find! Linux reading the file's codec as: Raw 24-bit PCM audio

But if this is a WAV with a .MP3 extension, I'm interested to know how SoundScrape appends the metadata correctly to the file. Do they require different methods (wav vs mp3) to append artwork, title, author, and year to file as metadata?

**Comment by Miserlou** [comment]
ID3 is actually separate to the MP3 spec, and can work with other formats:
https://en.wikipedia.org/wiki/ID3#Non-MP3-implementation_and_alternatives

**Comment by SimplicityGuy** [comment]
Seems like this is resolved.
