### ISSUE TITLE
Downloaded most recent number of tracks?

### ISSUE THREAD

**Issue by nazikus** [Miserlou/SoundScrape#59]
Is it possible to download a number of liked tracks of an artist, but the most recent ones only?
E.g., I don't want to download the whole huge list of liked tracks, but only the 10 recent ones.
`soundscrape https://soundcloud/<artist>/likes -n 10` will download 10 oldest liked tracks, but I don't see an option for recent ones.
Thanks

**Comment by nazikus** [comment]
ok. there's an inconsistency between these two:

    soundscrape https://soundcloud/<artist>/likes -n 10  # downloads from the end of a likes-list

and 

    soundscrape <artist> -l -n 10  # downloads from the start of a likes-list

(i guess it's not really an issue)

**Comment by Miserlou** [comment]
If you could actually supply the artist that you tested this on that'd help, it actually matters since SC moved their API.
