### ISSUE TITLE
No Module named mutagen.mp3

### ISSUE THREAD

**Issue by TetraEtc** [Miserlou/SoundScrape#60]
So I just installed SoundScrape and I can't manage to make it work.

```Stewarts-iMac:Music Stewart$ soundscrape https://soundcloud.com/ccpgames/sets/eve-online-in-game-tracks
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/soundscrape", line 7, in <module>
    from soundscrape.soundscrape import main
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 13, in <module>
    from mutagen.mp3 import MP3, EasyMP3
ImportError: No module named mutagen.mp3```

**Comment by ehemsley** [comment]
I installed soundscrape using
`pip install --user soundscrape`
and had this same issue. 
I solved it by using
`pip install --user mutagen`

I assume this is because soundscrape should include mutagen as a dependency.

**Comment by TetraEtc** [comment]
I just did `pip install soundscrape` so used `pip install mutagen` and it worked. 

I'll create a PR for this

**Comment by alexgorbatchev** [comment]
Just did `pip install soundscrape` and `mutagen` was missing. I suppose this patch hasn't been released yet?

**Comment by TetraEtc** [comment]
PR #61 fixes the issue but @Miserlou hasn't merged it yet

**Comment by Miserlou** [comment]
Should be fixed in latest version, although dunno if it'll work with pip3 anymore.

**Comment by TetraEtc** [comment]
Just tested using pip3, works fine as far as I can see
