### ISSUE TITLE
Downloading list of likes stops at 170 tracks

### ISSUE THREAD

**Issue by tyhallcsu** [Miserlou/SoundScrape#65]
when I run:

`$ soundscrape sharmanhall -l`

stops at 170 songs. last track it downloaded:

Downloading: SAFIA - You Are The One
[################################] 3534/3534 - 00:00:04

**Comment by tyhallcsu** [comment]
Looks like this fixes it:
https://github.com/Miserlou/SoundScrape/pull/54/commits/4883af2c164f30bbdb27bf000979f356e979a6cb

**Comment by spencerthayer** [comment]
Has 4883af2 been merged into the master?

**Comment by SimplicityGuy** [comment]
Seems like this is resolved.
