### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by iwfmp** [Miserlou/SoundScrape#70]
I tried to run the command from my terminal:
``` pip3 install soundscrape ```

it returns an error:
``` No files/directories in /tmp/pip-build-hc6mbno9/soundscrape/pip-egg-info (from PKG-INFO) ```

I tried installing other packages from other sources, and it works perfectly.

**Comment by PanderMusubi** [comment]
Try installing as much as needed python3- packages with apt-get as you see pulled in at /usr/local/lib/python3.5/dist-packages Remove those that you could inatll from that directory and try pip3 install again. That worked for me.

**Comment by Miserlou** [comment]
Can't reproduce, sorry. Works for me.
