### ISSUE TITLE
Thread for specific songs/tracks found to be "not downloadable."

### ISSUE THREAD

**Issue by tyhallcsu** [Miserlou/SoundScrape#77]
`The Presets - Pacifica Deluxe Mix is not downloadable.`

Link:
https://soundcloud.com/modularpeople/the-presets-pacifica-deluxe

**Comment by tyhallcsu** [comment]
`Love Sosa (RL Grime Remix) - Chief Keef is not downloadable.`

Link:
https://soundcloud.com/rlgrime/love-sosa-rl-grime-remix

**Comment by Miserlou** [comment]
Oh man, Love Sosa doesn't work? Can't allow that..

**Comment by Miserlou** [comment]
Works for me.. are you using the latest Soundscrape?

pip install soundscrape --upgrade

**Comment by tyhallcsu** [comment]
Whoops, I have been using this:

https://github.com/Miserlou/SoundScrape/pull/54/commits/4883af2c164f30bbdb27bf000979f356e979a6cb

This script allows downloading like list above 200 tracks.

**Comment by Miserlou** [comment]
Ah, gotcha. Do you want clean up that PR so that it merges with the latest and I'll update the deployed version?

**Comment by jabui** [comment]
I can try clean this up later today

On Thu, May 5, 2016 at 10:42 AM Rich Jones <notifications@github.com> wrote:

> Ah, gotcha. Do you want clean up that PR so that it merges with the latest
> and I'll update the deployed version?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Miserlou/SoundScrape/issues/77#issuecomment-217048438>
>
-- 
Zach

**Comment by tyhallcsu** [comment]
Sure, ill take a look -- ill checkout branches when i have time to thorough inspect conflicts but,
at quick inspection it might be the pagination  -- line 108 was modified to be:
`resolved = client.get('/users/'+userId+'/favorites', limit=200, linked_partitioning=1)`
because Soundcloud API doesn't explicitly support pagination. There is an undocumented parameter you can use linked_partitioning=1, that will add next_href to the response.

This seems to be what maxed download of likes at 200 - that's the max return from API.
https://developers.soundcloud.com/blog/offset-pagination-deprecated

**Comment by Miserlou** [comment]
Really big one: deathgrips just doesn't work entirely. Just nothing happens.

~/Music $ soundscrape deathgrips
~/Music $

**Comment by Miserlou** [comment]
Pushed for individual deathgrips tracks "fixed", but still quite hideous. More work to do to make it work properly.

**Comment by Miserlou** [comment]
Fixed! W000t!
