### ISSUE TITLE
Fuck SoundCloud

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/SoundScrape#78]
SoundCloud deleted my account, along with all of my original music, without warning or possibility for appeal. Somebody needs to donate a new API key for SoundScrape to work again, or even better, we need to strip out the _pysoundcloud_ dependency, which was being actively crippled anyway, and replace it with something entirely parser based.

**Comment by Miserlou** [comment]
Why the fuck would they make an API and a client library if they didn't want people to use it? Gah, I'm so pissed!

**Comment by injectedfusion** [comment]
I'll work on clearing out my music, and donate my API, I was working on a
similar project but having a front end. Your code, skills, and development
is far beyond mine. I can send it to you via private email in 24 hours.

-InjectedFusion

**Comment by Miserlou** [comment]
That would be very much appreciated. Please email miserlou@gmail.com to discuss further.

**Comment by alexgorbatchev** [comment]
I'm sorry this happened :( it sucks

**Comment by spencerthayer** [comment]
Out of curiosity do you still need an API?
