### ISSUE TITLE
global name 'OldID3' is not defined

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/SoundScrape#79]
$ sof https://soundcloud.com/tune-collective/bedown
Downloading: TOP $HELF & TA$C!ONE - Be Down
[################################] 3037/3037 - 00:00:01
global name 'OldID3' is not defined

This just started happening. IDK yet.

**Comment by tyhallcsu** [comment]
Same error is generated with this track:

https://soundcloud.com/3lau/rosesandmoney

**Comment by Miserlou** [comment]
Fixed. This was just fat fingers.
