### ISSUE TITLE
group the downloaded files

### ISSUE THREAD

**Issue by vrraghy** [Miserlou/SoundScrape#8]
This works well, and here's a feature request. Or two.

- For each user, there could be a folder created & all the sounds put into them.
- When a folder already exists, the sounds already downloaded could be skipped & only the rest could be fetched again.

Thank you!

**Comment by Miserlou** [comment]
SoundScrape is meant to be more like 'curl' or 'wget', just downloading in place.

Maybe I could add a --group option to put it into an /Artist Name/Artist Name - Song Name.mp3 format but I don't have plans to do this at this time. I would accept a PR which did this though.

**Comment by Miserlou** [comment]
Fixed in 0.14.0+
