### ISSUE TITLE
no albumart in bandcamp downloads

### ISSUE THREAD

**Issue by CaMeLCaseError** [Miserlou/SoundScrape#89]
hi,

i just downloaded an album and inividual track on bandcamp and don't have album art in the resulting mp3 - (but works e.g. on soundcloud)

also I get the warning when downloading from bandcamp:

soundscrape https://xxxxx.bandcamp.com/track/bla
[################################] 580/580 - 00:00:00
'int' object has no attribute 'encode'

:)

**Comment by pydo** [comment]
Can you post the real url to the bandcamp track? Also I fixed the warning message in one of my PRs.

**Comment by Miserlou** [comment]
Yeah, I'll need the actual address to be able to reproduce please!

**Comment by Miserlou** [comment]
Int cast is fixed in lastest version on pip.

**Comment by CaMeLCaseError** [comment]
after a pip install upgrade it was now fixed for me too - and also the album art is working again. many thanks for the quick responses :)
