### ISSUE TITLE
Add custom domain bandcamp support

### ISSUE THREAD

**Issue by RAnders00** [Miserlou/SoundScrape#91]
Currently, sites like http://music.monstercat.com/ are not supported. They use the same page layout and services like the xxx.bandcamp.com sites, so it should be possible to do it.

**Comment by Miserlou** [comment]
Great one, thanks!

From my phone..

**Comment by Miserlou** [comment]
Just pushed a fix to master so that you can do 

soundscrape -b http://music.monstercat.com/

Must include the full protocol URL. Will publish if it passes tests..

**Comment by Miserlou** [comment]
Fixed in 0.25.2
