### ISSUE TITLE
arguments not working properly

### ISSUE THREAD

**Issue by skandix** [Miserlou/SoundScrape#94]
recently installed soundscrape on a fairly new debian install, but the arguments seems like it's not working properly.. in this example i want to download 5 songs from each artist, but when it have got 5 songs it just continues downloading more songs from that artist ;_; 
https://asciinema.org/a/0bcupj5ijli0cb9c0bv3xo3nt

scrape.sh is a script that is generated by a python script i wrote to make it easier to download everyone i follow on my soundcloud account, or anyone's else followers... https://github.com/skandix/SoundcloudFollowerScraper

**Comment by Miserlou** [comment]
It's possible that -n no longer works with certain artists that use the undocumented new API. Thank you for reporting.

If you find the 'followers' downloader useful, I would also be interested in having that as a feature in SoundScrape. Feel free to send a pull request for that!

**Comment by Miserlou** [comment]
Fixed in 0.26.1
